######################################################################
# Automatically generated by qmake (2.01a) ven. oct. 14 18:42:29 2016
######################################################################

TEMPLATE = app
TARGET = smoothTxt
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
SOURCES += main.cpp \
	CMainWindow.cpp \
    CEditWidget.cpp

FORMS += \
    CMainWindow.ui

HEADERS += \
	CMainWindow.h \
	../common.h \
    CEditWidget.h
