######################################################################
# Automatically generated by qmake (2.01a) ven. oct. 14 18:42:29 2016
######################################################################

TEMPLATE = app
TARGET = createLDR
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
SOURCES += traite.cpp
